export type Language = "en" | "es"

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.subtitle": "Investment Analysis by",
    "header.report": "Investment Analysis Report",
    "header.profile": "profile",

    // Toolbar
    "toolbar.filter": "Filter",
    "toolbar.all": "All",
    "toolbar.buy": "Buy",
    "toolbar.hold": "Hold",
    "toolbar.sell": "Sell",
    "toolbar.search": "Search assets...",
    "toolbar.print": "Print / PDF",

    // Executive Summary
    "executive.label": "Executive Summary",

    // Macro Environment
    "macro.title": "Macro Environment",
    "macro.rates": "Rates",
    "macro.inflation": "Inflation",
    "macro.georisk": "Geo Risk",

    // Portfolio Allocation
    "allocation.title": "Recommended Portfolio Allocation",

    // Cross-Sector Insights
    "insights.kicker": "Cross-Sector",
    "insights.title": "Insights",

    // Top Picks
    "picks.title": "Risk-Adjusted Top Picks",
    "picks.empty": "No picks match the current filter.",
    "picks.riskAdj": "Risk-Adj Score",
    "picks.confidence": "Confidence",
    "picks.risk": "Risk",
    "picks.topPick": "Top pick:",
    "picks.na": "N/A",

    // Sector Overview
    "sectors.kicker": "Overview",
    "sectors.title": "Sectors",
    "sectors.dataUnavailable": "Data unavailable",

    // Detailed Analysis
    "analysis.kicker": "Analysis",
    "analysis.title": "Detailed Breakdown",
    "analysis.news": "Key News",
    "analysis.social": "Social Highlights",

    // Table columns
    "table.asset": "Asset",
    "table.price": "Entry",
    "table.24h": "Stop Loss",
    "table.7d": "Target 12m",
    "table.30d": "R/R",
    "table.ytd": "Score",
    "table.52w": "Conf / Risk",
    "table.sources": "Sources",
    "table.piotroski": "Piotroski",
    "table.social": "Social",
    "table.signal": "Signal",

    // Historical Accuracy
    "accuracy.kicker": "Tracking",
    "accuracy.title": "Historical Accuracy",
    "accuracy.empty": "No historical data yet. Accuracy tracking begins after your second report.",
    "accuracy.callsMade": "Calls Made",
    "accuracy.correct": "Correct",
    "accuracy.since": "Since",

    // Charts
    "charts.kicker": "Analytics",
    "charts.title": "Charts",
    "charts.confidence": "Sector Confidence",
    "charts.risk": "Risk vs Score",
    "charts.allocation": "Portfolio Allocation",
    "charts.buzz": "Social Buzz",
    "charts.riskScore": "Risk Score",
    "charts.adjScore": "Adj. Score",
    "charts.low": "Low",
    "charts.med": "Med",
    "charts.high": "High",
    "charts.medium": "Medium",

    // Disclaimer
    "disclaimer.label": "Disclaimer:",
    "disclaimer.text": "This report is generated by an AI-powered multi-agent research system and is for informational and educational purposes only. It does not constitute financial advice, investment recommendations, or solicitation to buy or sell any securities, cryptocurrencies, or commodities. Always consult a qualified financial advisor. Past performance is not indicative of future results. Tododeia and its creators assume no liability for investment losses.",

    // Footer
    "footer.tagline": "Open Source Investment Research",
    "footer.generated": "Generated:",

    // Error
    "error.noData": "No report data found. Run the investment analysis skill to generate a report.",

    // Sector names
    "sector.crypto": "Cryptocurrency",
    "sector.stocks": "Stock Market",
    "sector.materials": "Commodities & Materials",
    "sector.cash": "Cash",
    "sector.crypto.short": "Crypto",
    "sector.stocks.short": "Stocks",
    "sector.materials.short": "Materials",
    "sector.cash.short": "Cash",

    // Portfolio
    "portfolio.kicker": "My Portfolio",
    "portfolio.title": "Portfolio Tracker",
    "portfolio.tab": "My Portfolio",
    "portfolio.tab.report": "Report",
    "portfolio.addBtn": "Add to Portfolio",
    "portfolio.qty": "Qty:",
    "portfolio.confirm": "Confirm",
    "portfolio.added": "Added to portfolio",
    "portfolio.owned": "shares",
    "portfolio.empty": "Your portfolio is empty.",
    "portfolio.emptyHint": "Click \"+ Add to Portfolio\" on any pick card to start tracking.",
    "portfolio.clearAll": "Clear All",
    "portfolio.clearConfirm": "Remove all positions? This cannot be undone.",
    "portfolio.positions": "Positions",
    "portfolio.invested": "Total Invested",
    "portfolio.totalPnl": "Total P&L",
    "portfolio.col.asset": "Asset",
    "portfolio.col.date": "Bought",
    "portfolio.col.qty": "Qty",
    "portfolio.col.buyPrice": "Buy Price",
    "portfolio.col.cost": "Cost Basis",
    "portfolio.col.current": "Current",
    "portfolio.col.pnl": "P&L ($)",
    "portfolio.col.pnlPct": "P&L (%)",

    // Language picker
    "lang.title": "Choose your language",
    "lang.subtitle": "Elige tu idioma",
  },
  es: {
    // Header
    "header.subtitle": "Análisis de Inversión por",
    "header.report": "Reporte de Análisis de Inversión",
    "header.profile": "perfil",

    // Toolbar
    "toolbar.filter": "Filtro",
    "toolbar.all": "Todos",
    "toolbar.buy": "Comprar",
    "toolbar.hold": "Mantener",
    "toolbar.sell": "Vender",
    "toolbar.search": "Buscar activos...",
    "toolbar.print": "Imprimir / PDF",

    // Executive Summary
    "executive.label": "Resumen Ejecutivo",

    // Macro Environment
    "macro.title": "Entorno Macroeconómico",
    "macro.rates": "Tasas",
    "macro.inflation": "Inflación",
    "macro.georisk": "Riesgo Geo",

    // Portfolio Allocation
    "allocation.title": "Asignación de Portafolio Recomendada",

    // Cross-Sector Insights
    "insights.kicker": "Multi-Sector",
    "insights.title": "Perspectivas",

    // Top Picks
    "picks.title": "Mejores Selecciones Ajustadas al Riesgo",
    "picks.empty": "Ninguna selección coincide con el filtro actual.",
    "picks.riskAdj": "Puntaje Ajustado",
    "picks.confidence": "Confianza",
    "picks.risk": "Riesgo",
    "picks.topPick": "Top pick:",
    "picks.na": "N/D",

    // Sector Overview
    "sectors.kicker": "Vista General",
    "sectors.title": "Sectores",
    "sectors.dataUnavailable": "Datos no disponibles",

    // Detailed Analysis
    "analysis.kicker": "Análisis",
    "analysis.title": "Desglose Detallado",
    "analysis.news": "Noticias Clave",
    "analysis.social": "Destacados en Redes",

    // Table columns
    "table.asset": "Activo",
    "table.price": "Entrada",
    "table.24h": "Stop Loss",
    "table.7d": "Target 12m",
    "table.30d": "R/R",
    "table.ytd": "Score",
    "table.52w": "Conf / Riesgo",
    "table.sources": "Fuentes",
    "table.piotroski": "Piotroski",
    "table.social": "Social",
    "table.signal": "Señal",

    // Historical Accuracy
    "accuracy.kicker": "Seguimiento",
    "accuracy.title": "Precisión Histórica",
    "accuracy.empty": "Sin datos históricos aún. El seguimiento de precisión comienza después de tu segundo reporte.",
    "accuracy.callsMade": "Llamadas",
    "accuracy.correct": "Correctas",
    "accuracy.since": "Desde",

    // Charts
    "charts.kicker": "Analítica",
    "charts.title": "Gráficos",
    "charts.confidence": "Confianza por Sector",
    "charts.risk": "Riesgo vs Puntaje",
    "charts.allocation": "Asignación del Portafolio",
    "charts.buzz": "Actividad Social",
    "charts.riskScore": "Puntaje de Riesgo",
    "charts.adjScore": "Puntaje Adj.",
    "charts.low": "Bajo",
    "charts.med": "Med",
    "charts.high": "Alto",
    "charts.medium": "Medio",

    // Disclaimer
    "disclaimer.label": "Aviso Legal:",
    "disclaimer.text": "Este reporte es generado por un sistema de investigación multi-agente impulsado por IA y es solo para fines informativos y educativos. No constituye asesoramiento financiero, recomendaciones de inversión, ni solicitud para comprar o vender valores, criptomonedas o materias primas. Siempre consulte a un asesor financiero calificado. El rendimiento pasado no es indicativo de resultados futuros. Tododeia y sus creadores no asumen responsabilidad por pérdidas de inversión.",

    // Footer
    "footer.tagline": "Investigación de Inversión de Código Abierto",
    "footer.generated": "Generado:",

    // Error
    "error.noData": "No se encontraron datos del reporte. Ejecuta el skill de análisis de inversión para generar un reporte.",

    // Sector names
    "sector.crypto": "Criptomonedas",
    "sector.stocks": "Mercado de Valores",
    "sector.materials": "Materias Primas",
    "sector.cash": "Efectivo",
    "sector.crypto.short": "Cripto",
    "sector.stocks.short": "Acciones",
    "sector.materials.short": "Materias",
    "sector.cash.short": "Efectivo",

    // Portfolio
    "portfolio.kicker": "Mi Portafolio",
    "portfolio.title": "Seguimiento de Portafolio",
    "portfolio.tab": "Mi Portafolio",
    "portfolio.tab.report": "Reporte",
    "portfolio.addBtn": "Agregar al Portafolio",
    "portfolio.qty": "Cant.:",
    "portfolio.confirm": "Confirmar",
    "portfolio.added": "Agregado al portafolio",
    "portfolio.owned": "acciones",
    "portfolio.empty": "Tu portafolio está vacío.",
    "portfolio.emptyHint": "Haz clic en \"+ Agregar al Portafolio\" en cualquier tarjeta para comenzar.",
    "portfolio.clearAll": "Limpiar Todo",
    "portfolio.clearConfirm": "¿Eliminar todas las posiciones? Esta acción no se puede deshacer.",
    "portfolio.positions": "Posiciones",
    "portfolio.invested": "Total Invertido",
    "portfolio.totalPnl": "P&L Total",
    "portfolio.col.asset": "Activo",
    "portfolio.col.date": "Comprado",
    "portfolio.col.qty": "Cant.",
    "portfolio.col.buyPrice": "Precio Compra",
    "portfolio.col.cost": "Costo Base",
    "portfolio.col.current": "Actual",
    "portfolio.col.pnl": "P&L ($)",
    "portfolio.col.pnlPct": "P&L (%)",

    // Language picker
    "lang.title": "Choose your language",
    "lang.subtitle": "Elige tu idioma",
  },
}
